# Generated by Django 4.2.1 on 2024-06-08 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="todo",
            name="finishead",
            field=models.DateField(null=True),
        ),
    ]
